name: Remote CSV Update
on:
  repository_dispatch:
    types: [add_new_link]

jobs:
  update-csv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Append Data
        run: |
          # The data comes from the "client_payload" sent by your website
          echo "${{ github.event.client_payload.line }}" >> links.csv
          
      - name: Commit and Push
        run: |
          git config --global user.name "system-bot"
          git config --global user.email "bot@github.com"
          git add links.csv
          git commit -m "Remote update: ${{ github.event.client_payload.title }}"
          git push
